services:
  postgres-hackaton-api:
    container_name: hackaton-api-postgres
    image: postgres:alpine
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: hackaton-api
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hackaton-api-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: hackaton-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
      - '5555:5555'
    env_file: .env
    depends_on:
      postgres-hackaton-api:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql://postgres:docker@postgres-hackaton-api:5432/hackaton-api?schema=public'
      API_PORT: 3333
    networks:
      - hackaton-api-network

networks:
  hackaton-api-network:
    driver: bridge

volumes:
  postgres-data:
