FROM node:20-alpine

WORKDIR /app

# Instala as dependências necessárias para o Prisma no ambiente Alpine
RUN apk add --no-cache openssl

# Copia os arquivos necessários
COPY package.json package-lock.json ./
COPY prisma ./prisma

# Instala as dependências e Gera o Prisma Client
RUN npm install && npx prisma generate

# Comando para executar as migrações
CMD ["npx", "prisma", "migrate", "deploy"]