apiVersion: v1
kind: Service
metadata:
  name: api-tech-challenge-sso-service
  namespace: tech-challenge-group-4
  labels:
    name: api-tech-challenge-sso-service
spec:
  type: NodePort
  selector:
    app: api-tech-challenge-sso
  ports:
    - name: api-port
      protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 31333
